// Helpers for building image URLs that match the backend FileStorageService layout.
//
// Uploads are stored as `{yyyy}/{MM}/{uuid}.{ext}` and the backend writes a
// `{uuid}_thumb.jpg` next to each original. Use the thumb URL in dense grid
// views (the gallery page) and the full URL when the user zooms in.
//
// The DB stores either:
//   - just the file name:           "uuid.webp"               (legacy rows)
//   - or the date-partitioned path: "2026/06/uuid.webp"       (new rows)
// Both work — these helpers only swap the extension/suffix.

/**
 * Returns the thumbnail URL for an image. The thumbnail is a small JPEG copy
 * generated by the backend on upload. Falls back to the original URL if the
 * input doesn't look like an image filename.
 *
 * Example:
 *   thumbUrl("/uploads/2026/06/abc-123.webp")  →  "/uploads/2026/06/abc-123_thumb.jpg"
 *   thumbUrl("abc-123.webp")                   →  "abc-123_thumb.jpg"
 */
export function thumbUrl(url) {
  if (!url || typeof url !== 'string') return url;
  // Match the LAST dot-extension (jpg/jpeg/png/gif/webp). Replace with _thumb.jpg.
  return url.replace(/\.(webp|jpe?g|png|gif)$/i, '_thumb.jpg');
}

/**
 * Identity helper — kept for symmetry so callers can write
 *   <img src={fullUrl(img.imageUrl)} />
 * even if we later change the way full URLs are built (e.g. switch to R2 CDN).
 */
export function fullUrl(url) {
  return url;
}

/**
 * Normalises an arbitrary image reference (full URL, leading-slash path, or bare
 * filename) into a path under /uploads/. Used by the public catalog screens for
 * category and product images. Returns null for empty input.
 */
export function uploadsImgSrc(url) {
  if (!url) return null;
  if (url.startsWith('http')) return url;
  const clean = url.replace(/^\/+/, '').replace(/^uploads\//, '');
  return `/uploads/${clean}`;
}
